name: CI-CD-SyncS3-StaticWebSite-CloudFrontInvalidation
env:
  AWS_REGION_NAME : "us-east-1"

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-s3-bucket:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}

      - name: Show files in current dir
        run: ls -la
      
      - name: Run a aws s3 syncronization
        run: aws s3 sync . ${{ secrets.AWS_S3_BUCKET }} --exclude "*Lambda*" --exclude "*Polices*" --exclude "*.git*" --delete
        
      - name: Create CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
